name: CI
on:
  push:
    branches-ignore:    
      - master

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Configure poetry
        uses: abatilo/actions-poetry@v2
      - name: Poetry install
        run: poetry install
      - name: Setup just
        uses: extractions/setup-just@v1
      - name: Run lint
        run: just lint
